- name: check_jboss_source
  local_action: stat path=../files/{{ jboss_zip }}.zip
  register: source_jboss_tar_gz

- name: check if the joss_home exists
  stat: path="{{ jboss_config_dir }}"
  register: jboss_real_home_check

- name: copy installation jboss
  copy: src=files/{{ jboss_zip }}.zip dest={{ jboss_home }} owner={{ jboss_user }} group={{ jboss_group }} mode=0644


- name: unarchive {{ jboss_zip }}.zip
  unarchive:
    src: "{{ jboss_home }}/{{ jboss_zip }}.zip"
    dest: "{{ jboss_home }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    copy: no
  when: jboss_real_home_check.stat.isdir is not defined or not jboss_real_home_check.stat.isdir

- name: create link simbolic
  shell: cd {{ jboss_home }} && ln -s {{ jboss_home }}/{{ jboss_ver }} jboss-eap

- name: create directory module jdbc
  file: path={{ jboss_home }}/jboss-eap/modules/system/layers/base/com owner={{ jboss_user }} group={{ jboss_group }} mode=0775 state=directory recurse=no

- name: Driver jdbc oracle
  copy: src=files/oracle.tar.gz dest={{ jboss_home }}/jboss-eap/modules/system/layers/base/com owner={{ jboss_user }} group={{ jboss_group }} mode=0644
  
- name: uncompress driver jdbc oracle
  shell: cd {{ jboss_home }}/jboss-eap/modules/system/layers/base/com && tar xfz oracle.tar.gz && rm -f oracle.tar.gz

- name: create folder master
  shell: cp -R {{ jboss_home }}/jboss-eap/domain {{ jboss_home }}/jboss-eap/master
  when: inventory_hostname == groups['jboss-servers'][0]

- name: create folder slave1
  shell: cp -R {{ jboss_home }}/jboss-eap/domain {{ jboss_home }}/jboss-eap/{{ ansible_hostname }}

- name: clean configuration slave host.xml
  file: path="{{jboss_home}}/jboss-eap/{{ansible_hostname}}/configuration/host.xml" state=absent

- name: clean configuration slave domain.xml
  file: path="{{jboss_home}}/jboss-eap/{{ansible_hostname}}/configuration/domain.xml" state=absent

- name: delete sorgente zip JBOSS {{ jboss_zip }}.zip
  file: state=absent path="{{ jboss_home }}/{{ jboss_zip }}.zip"

- name: create directory scripts
  file: path={{ jboss_home }}/scripts owner={{ jboss_user }} group={{ jboss_group }} mode=0775 state=directory recurse=no

- name: copy script start master
  template:
    src: jboss_eap_master.sh
    dest: "{{ jboss_home }}/scripts/jboss-eap-master.sh"
    mode: 0755
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy script start init master
  template:
    src: jboss_eap_init_master.sh
    dest: "{{ jboss_home }}/scripts/jboss-eap-init-master.sh"
    mode: 0755
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy script start controller
  template:
    src: jboss_eap_controller.sh
    dest: "{{ jboss_home }}/scripts/jboss-eap-{{ansible_hostname}}.sh"
    mode: 0775

- name: copy script start init controller
  template:
    src: jboss-eap-init-controller.sh
    dest: "{{ jboss_home }}/scripts/jboss-eap-init-{{ansible_hostname}}.sh"
    mode: 0775

- name: copy add-user.sh
  template:
    src: add-user.sh
    dest: "{{ jboss_home }}/jboss-eap/bin/add-user.sh"
    mode: 0775

- name: create directory jboss.conf.d
  file: path={{ jboss_home }}/jboss-eap/jboss.conf.d owner={{ jboss_user }} group={{ jboss_group }} mode=0775 state=directory recurse=no

- name: create folder rilasci
  file: path={{ jboss_home }}/rilasci owner={{ jboss_user }} group={{ jboss_group }} mode=0775 state=directory recurse=no
  when: inventory_hostname == groups['jboss-servers'][0]

- name: crypt secret
  shell: echo -n "{{ jbossadminpassword }}" | base64
  register: secret
- set_fact: secret={{ secret.stdout }}

- name: copy host-slave.xml
  template:
    src: "{{jboss_ver}}_host-slave.xml"
    dest: "{{jboss_home}}/jboss-eap/{{ansible_hostname}}/configuration/host-slave.xml"
    mode: 0755
    
- name: copy host.xml "{{jboss_ver}}""
  template:
    src: "{{jboss_ver}}_host.xml"
    dest: "{{jboss_home}}/jboss-eap/{{ansible_hostname}}/configuration/host.xml"
    mode: 0755
  when: jboss_ver == "jboss-eap-6.4"

- name: copy enviroment configuration master jboss-master.conf
  template: src=jboss-master.conf dest={{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf mode=0777
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy enviroment configuration servers jboss-{{ansible_hostname}}.conf
  template: src=jboss-controller.conf dest={{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-{{ansible_hostname}}.conf mode=0777

- name: copy enviroment configuration master domain.xml
  template: src="{{jboss_ver}}_MASTER_domain.xml" dest={{ jboss_home }}/jboss-eap/master/configuration/domain.xml
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy enviroment configuration master host-slave.xml
  template: src="{{jboss_ver}}_MASTER_host-slave.xml" dest={{ jboss_home }}/jboss-eap/master/configuration/host-slave.xml
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy enviroment configuration master host.xml
  template: src="{{jboss_ver}}_MASTER_host.xml" dest={{ jboss_home }}/jboss-eap/master/configuration/host.xml
  when: inventory_hostname == groups['jboss-servers'][0]

- name: copy enviroment configuration master host-master.xml
  template: src="{{jboss_ver}}_MASTER_host-master.xml" dest={{ jboss_home }}/jboss-eap/master/configuration/host-master.xml
  when: inventory_hostname == groups['jboss-servers'][0]

- name: Create default JBoss host user
  shell: ". {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf && cd {{ jboss_home }}/jboss-eap/bin && ./add-user.sh -r ManagementRealm -u {{item.name}} -p {{item.password}}"
  with_items:
    - { name: 'admin', password: '{{jbossadminpassword}}' }
    - { name: 'host', password: '{{jbossadminpassword}}' }
  when: inventory_hostname == groups['jboss-servers'][0]

- name: Create default JBoss host user slave
  shell: ". {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-{{ansible_hostname}}.conf && cd {{ jboss_home }}/jboss-eap/bin && ./add-user.sh -r ManagementRealm -u {{item.name}} -p {{item.password}}"
  with_items:
    - { name: 'admin', password: '{{jbossadminpassword}}' }
    - { name: 'host', password: '{{jbossadminpassword}}' }
  when: inventory_hostname == groups['jboss-servers'][1]





