- name: check PACKAGE WAR2
  shell: . {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf; cd {{jboss_home}}/jboss-eap/bin && ./jboss-cli.sh -c "deployment-info --server-group={{jbossservergroups}}B --name={{PACKAGE}}.war2" --controller={{jboss_dc}}:9990
  register: output_package_war2
  when: inventory_hostname == groups['jboss-servers'][0]

- debug: var=output_package_war2

- name: undeploy PACKAGE war2
  shell: . {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf; cd {{jboss_home}}/jboss-eap/bin && ./jboss-cli.sh -c 'undeploy {{PACKAGE}}.war2 --server-groups={{jbossservergroups}}B' --controller={{jboss_dc}}:9990
  register: undeploy_war2
  when: inventory_hostname == groups['jboss-servers'][0] and output_package_war2.stdout is not defined

- name: deploy "{{PACKAGE}}".war2
  shell: . {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf; cd {{jboss_home}}/jboss-eap/bin && ./jboss-cli.sh -c "deploy {{jboss_home}}/rilasci/{{PACKAGE}}.war --name={{PACKAGE}}.war2 --runtime-name={{PACKAGE}}.war --server-groups={{jbossservergroups}}B" --controller={{jboss_dc}}:9990
  register: deploy_war2
  when: inventory_hostname == groups['jboss-servers'][0]

- name: check PACKAGE WAR2
  shell: . {{ jboss_home }}/jboss-eap/jboss.conf.d/jboss-master.conf; cd {{jboss_home}}/jboss-eap/bin && ./jboss-cli.sh -c "deployment-info --server-group={{jbossservergroups}}B --name={{PACKAGE}}.war2" --controller={{jboss_dc}}:9990
  register: output_package_war1
  when: inventory_hostname == groups['jboss-servers'][0] and deploy_war2.rc == 0

- debug: var=output_package_war2
